---
- name: Rest API Example [aciguru]
  hosts: apic
  connection: local
  gather_facts: False

  tasks:
    - name: Initiate lab clean up
      aci_rest:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        method: "delete"
        validate_certs: False
        path: "api/mo/uni/tn-aciguru.json"
